pipelines:
  - pipeline: form
    name: marg_together

datasets:
    # ncd20
  - name: newer_college_2020/short_experiment
    length: 6000
  # ncd21
  - name: newer_college_2021/stairs
    length: 6000
  # mcd
  - name: multi_campus/kth_day_06
    length: 6000
